[env:attiny412]
platform = https://github.com/platformio/platform-atmelmegaavr.git#v1.10.0
platform_packages = framework-arduino-megatinycore@https://github.com/SpenceKonde/megaTinyCore#2.6.11
board = ATtiny412
framework = arduino
upload_flags =
    --tool
    uart
    --device
    $BOARD
    --uart
    /dev/serial/by-id/usb-wch.cn_USB_Quad_Serial_0123456789-if04
    -b
    $UPLOAD_SPEED

upload_protocol = custom
upload_command = python3 ${platformio.packages_dir}/framework-arduino-megaavr-megatinycore/tools/prog.py $UPLOAD_FLAGS -f$SOURCE -a write

board_build.f_cpu = 5000000L    ; 5MHz CPU clock for low-power 3V coin-cell operation

build_flags =
  -Os
  -std=gnu++20
  -UMILLIS_USE_TIMERD0
  -DMILLIS_USE_TIMERNONE      ; no Arduino timekeeping ISR; modulation owns wake cadence
  -DDISABLE_TCD0_PWM=1        ; prevent Arduino from using TCD0 for analogWrite
  ; Tag ID:
  -DTAG_CUSTOMER_CODE=0x12
  -DTAG_SERIAL_NUMBER=0x3456789A
